FROM jenkins/jenkins:lts

USER root

# Instalar Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Agregar jenkins al grupo docker
RUN groupmod -g 999 docker && \
    usermod -aG docker jenkins

# Cambiar permisos del socket si existe
RUN chmod 666 /var/run/docker.sock 2>/dev/null || true

USER jenkins
