FROM jenkins/jenkins:lts

USER root

# Instalar Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Agregar jenkins al grupo docker
RUN usermod -aG docker jenkins || true

USER jenkins
